In [4]:
import pandas as pd
from tabfairgan import TFG

# Lade deinen bereinigten Datensatz
df = pd.read_csv("clean_data.csv")  
df

,Q1,Q2A,Q2B,Q2C,Q2D,Q2E,Q2F,Q2G,Q4A,Q4B,...,Q12I,Q13,Q14,Q15,Q16,Q17A,Q17B,Q17C,Q17D,Q17E
0,5,2,2.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,...,3.0,2.0,6.0,1.0,3.0,0.0,0.0,1.0,0.0,0.0
1,3,2,2.0,1.0,1.0,2.0,2.0,1.0,2.0,2.0,...,2.0,1.0,6.0,1.0,3.0,0.0,0.0,1.0,0.0,0.0
2,3,3,3.0,2.0,2.0,1.0,2.0,2.0,3.0,2.0,...,4.0,2.0,8.0,2.0,1.0,0.0,0.0,0.0,1.0,0.0
3,3,2,2.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,...,2.0,1.0,5.0,1.0,3.0,0.0,0.0,1.0,0.0,0.0
4,2,2,3.0,1.0,2.0,3.0,3.0,3.0,3.0,3.0,...,5.0,1.0,5.0,1.0,3.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
483,3,3,3.0,1.0,1.0,3.0,3.0,3.0,2.0,3.0,...,3.0,1.0,8.0,1.0,9.0,0.0,0.0,1.0,0.0,0.0
484,2,3,3.0,2.0,1.0,3.0,3.0,2.0,3.0,2.0,...,5.0,2.0,7.0,1.0,3.0,0.0,0.0,1.0,0.0,1.0
485,3,2,3.0,1.0,1.0,3.0,3.0,3.0,1.0,3.0,...,1.0,2.0,12.0,2.0,1.0,1.0,0.0,0.0,0.0,0.0
486,5,1,3.0,1.0,1.0,3.0,1.0,1.0,2.0,2.0,...,2.0,2.0,6.0,1.0,3.0,1.0,0.0,0.0,0.0,0.0
487,5,2,1.0,2.0,1.0,3.0,1.0,2.0,1.0,3.0,...,2.0,2.0,9.0,1.0,3.0,0.0,0.0,1.0,0.0,0.0

In [5]:
# Liste an kategorischen Spalten (z.â€¯B. alles mit 'Q' auÃŸer Geburtsjahr)
categorical_cols = [col for col in df.columns if not col.startswith("Q14")]

# Wandle diese Spalten in object
df[categorical_cols] = df[categorical_cols].astype("object")

In [6]:
# Zeilen mit NaN Werten entfernen
df.dropna(inplace=True)
df.reset_index(drop=True, inplace=True)
df

,Q1,Q2A,Q2B,Q2C,Q2D,Q2E,Q2F,Q2G,Q4A,Q4B,...,Q12I,Q13,Q14,Q15,Q16,Q17A,Q17B,Q17C,Q17D,Q17E
0,3,2,2.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,...,2.0,1.0,5.0,1.0,3.0,0.0,0.0,1.0,0.0,0.0
1,2,2,3.0,1.0,2.0,3.0,3.0,3.0,3.0,3.0,...,5.0,1.0,5.0,1.0,3.0,0.0,0.0,1.0,0.0,0.0
2,2,2,3.0,1.0,1.0,3.0,3.0,2.0,2.0,1.0,...,2.0,1.0,5.0,1.0,3.0,0.0,0.0,0.0,0.0,1.0
3,3,2,2.0,1.0,1.0,1.0,2.0,1.0,3.0,3.0,...,3.0,2.0,7.0,1.0,3.0,0.0,0.0,1.0,0.0,0.0
4,5,2,2.0,1.0,1.0,2.0,2.0,2.0,3.0,3.0,...,4.0,2.0,9.0,1.0,3.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,5,2,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,...,3.0,2.0,12.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
96,2,3,3.0,2.0,2.0,3.0,3.0,3.0,3.0,3.0,...,3.0,1.0,15.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
97,2,3,3.0,2.0,1.0,3.0,3.0,2.0,3.0,2.0,...,5.0,2.0,7.0,1.0,3.0,0.0,0.0,1.0,0.0,1.0
98,3,2,3.0,1.0,1.0,3.0,3.0,3.0,1.0,3.0,...,1.0,2.0,12.0,2.0,1.0,1.0,0.0,0.0,0.0,0.0
99,5,1,3.0,1.0,1.0,3.0,1.0,1.0,2.0,2.0,...,2.0,2.0,6.0,1.0,3.0,1.0,0.0,0.0,0.0,0.0

In [7]:
# Initialisiere TabFairGAN ohne Fairness Constraints
tfg = TFG(df, epochs=200, batch_size=256, device='cpu') 

# Trainiere das Modell
tfg.train()

# Generiere synthetische Daten
fake_df = tfg.generate_fake_df(num_rows=len(df))

# Speichere die synthetischen Daten ab
fake_df.to_csv("synthetic_data.csv", index=False)

/Users/laurenziubiemel/Downloads/Bierprojekt/Bierprojekt/venv/lib/python3.10/site-packages/sklearn/preprocessing/_data.py:2829: UserWarning: n_quantiles (2000) is greater than the total number of samples (100). n_quantiles is set to n_samples.
  warnings.warn(
Training Progress: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 200/200 [00:00<00:00, 2731.24it/s, Training for accuracy]

epoch 1
epoch 2
epoch 3
epoch 4
epoch 5
epoch 6
epoch 7
epoch 8
epoch 9
epoch 10
epoch 11
epoch 12
epoch 13
epoch 14
epoch 15
epoch 16
epoch 17
epoch 18
epoch 19
epoch 20
epoch 21
epoch 22
epoch 23
epoch 24
epoch 25
epoch 26
epoch 27
epoch 28
epoch 29
epoch 30
epoch 31
epoch 32
epoch 33
epoch 34
epoch 35
epoch 36
epoch 37
epoch 38
epoch 39
epoch 40
epoch 41
epoch 42
epoch 43
epoch 44
epoch 45
epoch 46
epoch 47
epoch 48
epoch 49
epoch 50
epoch 51
epoch 52
epoch 53
epoch 54
epoch 55
epoch 56
epoch 57
epoch 58
epoch 59
epoch 60
epoch 61
epoch 62
epoch 63
epoch 64
epoch 65
epoch 66
epoch 67
epoch 68
epoch 69
epoch 70
epoch 71
epoch 72
epoch 73
epoch 74
epoch 75
epoch 76
epoch 77
epoch 78
epoch 79
epoch 80
epoch 81
epoch 82
epoch 83
epoch 84
epoch 85
epoch 86
epoch 87
epoch 88
epoch 89
epoch 90
epoch 91
epoch 92
epoch 93
epoch 94
epoch 95
epoch 96
epoch 97
epoch 98
epoch 99
epoch 100
epoch 101
epoch 102
epoch 103
epoch 104
epoch 105
epoch 106
epoch 107
epoch 108
epoch 109
epoch 110
epoch 111
epoch 112
epoch 113
epoch 114
epoch 115
epoch 116
epoch 117
epoch 118
epoch 119
epoch 120
epoch 121
epoch 122
epoch 123
epoch 124
epoch 125
epoch 126
epoch 127
epoch 128
epoch 129
epoch 130
epoch 131
epoch 132
epoch 133
epoch 134
epoch 135
epoch 136
epoch 137
epoch 138
epoch 139
epoch 140
epoch 141
epoch 142
epoch 143
epoch 144
epoch 145
epoch 146
epoch 147
epoch 148
epoch 149
epoch 150
epoch 151
epoch 152
epoch 153
epoch 154
epoch 155
epoch 156
epoch 157
epoch 158
epoch 159
epoch 160
epoch 161
epoch 162
epoch 163
epoch 164
epoch 165
epoch 166
epoch 167
epoch 168
epoch 169
epoch 170
epoch 171
epoch 172
epoch 173
epoch 174
epoch 175
epoch 176
epoch 177
epoch 178
epoch 179
epoch 180
epoch 181
epoch 182
epoch 183
epoch 184
epoch 185
epoch 186
epoch 187
epoch 188
epoch 189
epoch 190
epoch 191
epoch 192
epoch 193
epoch 194
epoch 195
epoch 196
epoch 197
epoch 198
epoch 199
epoch 200